# Docs
# https://goreleaser.com/customization/builds/
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    id: "hello-world"
    goamd64:
      - v2
      - v3
    targets:
      - linux_amd64
#      - linux_arm64
#      - darwin_amd64
#      - darwin_arm64
#      - linux_arm
      - windows_amd64
    main: ./
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -extldflags '-static'
#      - -s -w
#      - -X main.version={{.Version}}
#      - -X main.commitSHA={{.FullCommit}}
#      - -X main.buildDate={{.Date}}

archives:
  - format: binary
    name_template: '{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_checksums.txt'